- openwisp-config/files/openwisp.agent
> [draft] Add support for template tags #34

- openwisp-config/files/openwisp.agent
> [agent] Fix spelling

- openwisp-config/files/openwisp-nossl.config
- openwisp-config/files/openwisp-ssl.config
- openwisp-config/files/openwisp.agent
- openwisp-config/files/openwisp.init
with good credentials (i think). Sry for my bad configuration
> Add a post reload hook after configuration successfully applied.

- README.rst
I've successfully tested openwisp-config with Openwrt v18.06.1
Fixes #55
> [doc] Update readme for OpenWRT v18.06.1

- openwisp-config/Makefile
- openwisp-config/files/lib/openwisp/net.lua
- openwisp-config/files/sbin/openwisp-get-address.lua
Added a more flexible and reusable function that is
used under the hood by `/usr/sbin/openwisp-get-address`.
> [lua] Refactored openwisp-get-address to use lib function

- openwisp-config/files/sbin/openwisp-uci-autoname.lua
- openwisp-config/tests/test_uci_autoname.lua
Closes #66 
@nemesisdesign Is this how you meant it to be?
> [tests] Fix test for autoname script

- .travis.yml
> [qa] Added commit message syle check #84

- README.rst
- openwisp-config/files/openwisp-nossl.config
- openwisp-config/files/openwisp-ssl.config
- openwisp-config/files/openwisp.agent
- openwisp-config/files/openwisp.init
> Add random bootup delay #100

- openwisp-config/files/openwisp.agent
> [agent] Update general device info on the controller after bootup #58

- README.rst
- openwisp-config/files/openwisp.agent
- openwisp-config/files/openwisp.init
Added configurable default hostname.
> [feature] Added configurable default hostname

- .travis.yml
- README.rst
> [chores] Upgraded openwisp-utils dependency for Travis builds

- openwisp-config/files/openwisp.agent
> [fix] Agent: output correct log message on post-registration-hook

- README.rst
- openwisp-config/files/openwisp.init
Make the procd respawn parameters configurable.
> [init] Add extra respawn parameters

- openwisp-config/files/openwisp.agent
> [fix] Fix HTTP response codes on newer cURL versions #142

- openwisp-config/files/openwisp.agent
> [fix] Verify downloaded tarball with configuration checksum #158

- .editorconfig
- .github/workflows/ci.yml
- README.rst
- install-dev.sh
- openwisp-config/files/lib/openwisp/net.lua
- openwisp-config/files/lib/openwisp/utils.lua
- openwisp-config/files/openwisp.agent
- openwisp-config/files/openwisp.init
- openwisp-config/files/sbin/openwisp-get-address.lua
- openwisp-config/files/sbin/openwisp-reload-config
- openwisp-config/files/sbin/openwisp-remove-default-wifi.lua
- openwisp-config/files/sbin/openwisp-restore-unmanaged.lua
- openwisp-config/files/sbin/openwisp-store-unmanaged.lua
- openwisp-config/files/sbin/openwisp-uci-autoname.lua
- openwisp-config/files/sbin/openwisp-update-config.lua
- openwisp-config/luaformat.config
- openwisp-config/tests/test_remove_default_wifi.lua
- openwisp-config/tests/test_restore_unmanaged.lua
- openwisp-config/tests/test_store_unmanaged.lua
- openwisp-config/tests/test_uci_autoname.lua
- openwisp-config/tests/test_update_bad_config.lua
- openwisp-config/tests/test_update_config.lua
- openwisp-config/tests/test_utils.lua
- qa-format
- run-qa-checks
- runbuild
> [qa] Add qa checks and formatting #147 #148

- .github/workflows/ci.yml
- install-dev.sh
See https://github.com/google-github-actions/setup-gcloud/issues/539.
> [ci] Changed google-github-actions/setup-gcloud to be pinned to @v0

- openwisp-config/files/openwisp.agent
@devkapilbansal smells like formatting change gone wrong.
> [fix] Fixed bogus redirection syntax

- README.rst
- openwisp-config/files/openwisp.agent
Allows forcing devices to register using their mac address instead of their hostname in all cases.
> [feature] Added default_hostname *

- openwisp-config/files/openwisp.agent
> [change] Log errors of openwisp-update-config in logd #168

- openwisp-config/files/openwisp.agent
If the agent fails to apply configuration for any reason, then
the openwisp logs since the last configuration update trigger is
sent to the controller.
Closes #182
> [feature] Added functionality to report errors to the controller #182

- openwisp-config/files/openwisp.agent
Added retry mechanism with random backoff for following functions:
- get_checksum
- download_configuration
- report_status
Closes #186
-------------
I have manually tested these changes with my device.
> [feature] Added retry mechanism with random backoff #186

- README.rst
Improved "Bootup Delay" explanation.
> [docs] Improved Bootup Delay explanation

- openwisp-config/Makefile
- openwisp-config/files/openwisp.agent
> [change] Moved package VERSION to `/usr/lib/openwisp-config/`

- README.rst
- openwisp-config/files/openwisp.agent
This implements the feature requested in #198.
> [feature] Add hotplug event to agent main loop #198

- openwisp-config/files/lib/openwisp/utils.lua
- runbuild
If tests fail, repeat the compilation with verbose output.
> [tests] Runbuild verbose output

- openwisp-config/files/sbin/openwisp-uci-autoname.lua
- openwisp-config/tests/config/network
- openwisp-config/tests/test_uci_autoname.lua
Maintain consistency with the naming used on OpenWISP.
Closes #199
> [change] Handle autonaming of network devices #199

- openwisp-config/Makefile
- openwisp-config/files/openwisp.hotplug
- N/A I have updated the documentation.
Related to #208
Automatically triggers a config check when the `management_interface` comes up,  updating the management IP address on the OpenWISP server.
> [feature] Added hotplug script for management_interface #208
