openwisp-config/files/openwisp.agent

I took advantage of this moment to refactor the curl registration call
which now should be more robust because the less predictable variables
are url-encoded before being sent via HTTP
Implements and closes #32

[agent] Send device information during registration #32

---

openwisp-config/files/openwisp.agent

The script `openwisp-restore-unmanaged.lua` is executed regardless of wether unmanaged sections are defined or not. This leads to an unwanted modification of the configuration if files exist in the unmanaged path.

[unmanaged] Prevent accidental execution of openwisp-restore-unmanaged.lua script

---

.travis.yml
openwisp-config/tests/test_utils.lua
runtests

- added travis.yml with **dependencies installation configuration.**
- added luacheck test command with parameters (_-d -a -r_) to filter unwanted warnings in **runtests script**
- after running runtests script
-- fixed **`accessing undefined variable uci`** warning by making **`uci`** global variable and assigning to `require('uci')`in `openwisp-config/tests/test_utils.lua` file
fixes #77 
this is a submission for **GCI task**- **Add travis-ci configuration for luacheck - OpenWISP**

Added Luacheck and travis.yml with install-config 

---

.travis.yml
install-dev.sh

`luacheck` is now called in the `runtests` script but it won't be installed through the `install-dev.sh` script. This PR fixes that.
Related question: is there a reason why `luafilesystem` and `luaunit` are not installed with `apt`?

[tests] Install lua-check in install-dev.sh

---

.luacheckrc
openwisp-config/files/lib/openwisp/net.lua
openwisp-config/files/lib/openwisp/utils.lua
openwisp-config/files/sbin/openwisp-remove-default-wifi.lua
openwisp-config/files/sbin/openwisp-restore-unmanaged.lua
openwisp-config/files/sbin/openwisp-store-unmanaged.lua
openwisp-config/files/sbin/openwisp-update-config.lua
openwisp-config/tests/test_remove_default_wifi.lua
openwisp-config/tests/test_restore_unmanaged.lua
openwisp-config/tests/test_store_unmanaged.lua
openwisp-config/tests/test_uci_autoname.lua
openwisp-config/tests/test_update_bad_config.lua
openwisp-config/tests/test_update_config.lua
openwisp-config/tests/test_utils.lua
runtests

Removes all filter flags from luacheck, and ensure it runs over the whole codebase
Fix all luacheck warnings that arise from this.
Closes #77

[luacheck] Run luacheck on all files and fix warnings

---

.travis.yml

The following errors arose when using https://config.travis-ci.com/explore:
[warn] on root: deprecated key: "sudo" (The key `sudo` has no effect anymore.)
~~[info] on root: missing os, using the default "linux"~~

[ci] Fix .travis.yml errors

---

openwisp-config/Makefile
openwisp-config/files/openwisp.agent

Give up registration only when 403, keep retrying in all other cases.
This allows the device to keep trying to register if there's a temporary server side issue or in case the self creation has been disabled: https://github.com/openwisp/django-netjsonconfig/pull/162

[agent] Give up registration only when 403

---

install-dev.sh
runtests

Fixed setup problems.
1. In `install-dev.sh` installation procedure of json-c needed to be updated. :-)
2. Failing chained commands were not stopping the install script immediately, changed that by using `command || {exit 1}` trick.
3. In `./runtests` scripts, changed `luacheck . -a` -> `luacheck ./openwisp-config/ -a` because if I do `./runbuild` with BUILD_DIR as `~/.build`, runtests wouldn't work again, I suppose other developers would want to build for testing in this directory itself as well, hence made this change.
Let me know if BUILD_DIR should be elsewhere and I should reverse this change.
Closes #105

[setup] fixed install & runtests scripts

---

openwisp-config/files/openwisp.agent

If the headers get changed, the check was case sensitive. That
prevented the client from connecting. This changes the check to be
case insensitive instead.
Fixes #110

[agent] Case sensitivity when checking header #110

---

openwisp-config/files/openwisp.agent

Show entire error message in logs instead of the last line only on failed auto-registration, Fixes #42

Show entire error message in logs on failed auto-registration #42

---

README.rst
openwisp-config/files/openwisp.agent
openwisp-config/files/openwisp.init

This patch adds 2 config options for the default config test.
1. `test_delay` is a time in seconds to wait after applying the configuration before the config test is started. This prevents that the test is successfully completed before the change is even applied by the services.
2. `test_retries` is the number of retries used by the test. Applying configuration changes can take quite some time (for example enabling a wwan connection with trying several networks) and in such cases the config test would fail after 3 retries with the configuration change not even fully applied by the services.

[agent] Add config options post_reload_delay and test_retries

---

openwisp-config/files/openwisp.agent

Otherwise it's possible that the test fails although the regular checksum fetch succeeds.
I had this issue because the overridden value 5 for `--connect-timeout` and `--max-time` was too low for the specific connection of the device.
In general it makes sense that the test behaves exactly like the regular checksum fetch.

[agent] Use configured curl timeout values in default test

---

openwisp-config/files/openwisp.agent

Adding the --fail flag to curl makes it exit with a non zero
exit code in case the server respond with an HTTP status code
which is not 200 OK.
Without this fix, a bad response is interpreted as a valid configuration
and the agent removes the old configuration, then installs the new configuration,
which fails and the router remains with an empty configuration,
effectively causing a disrupation of service.
Fixes #125

[fix] Ensured config download error is detected #125

---

openwisp-config/files/openwisp.agent

This fixes 2 problems:
1. If the openwisp-config daemon is restartet (e.g. by the openwisp-
controller via ssh) after it already downloaded the latest checksum
but before it has applied the configuration, all further calls of
configuration_changed() (until CONFIGURATION_CHECKSUM is deleted,
e.g. by a reboot) will imply that everything is already up-to-date,
although the configuration was never applied.
2. prevents the configuration from being downloaded and written again
after a reboot.

[agent] Make configuration checksum persistent

---

openwisp-config/files/openwisp.agent

The openwisp agent modifies the configuration on first contact by
rewriting all anonymous uci sections into named uci sections. This
causes almost all services to be restarted even though the configuration
has not really changed. To prevent this from happening, the md5sums are
rewritten after calling openwisp-uci-autoname. This will reload only
those services whose configuration has actually been changed.

[agent] Fix service reload handling for unnamed uci sections

---

openwisp-config/files/openwisp.agent

Use SIGUSR1 to interrupt the interval sleep.
This can be used by the openwisp-controller instead of restarting the
complete openwisp-agent.

[change] agent: add SIGUSR1 handler

---

openwisp-config/files/openwisp.agent

[fix] Handle agent crashing when registration not successful #156

---

openwisp-config/Makefile

The BUILD_VARIANT variable was left lingering in the Makefile.

[chores] Removed obsolete BUILD_VARIANT from Makefile

---

openwisp-config/files/openwisp.agent

If the interface specified in the mac_interface is not available on the system, the agent should take the first non-loopback interface available, but this behavior was broken inadvertently.

[fix] Fixed register bug when mac_interface is not present

---

openwisp-config/files/openwisp.agent

[fix] Include all modified files in backup #206

---

README.rst
openwisp-config/Makefile
openwisp-config/files/openwisp.agent
openwisp-config/files/openwisp.init
openwisp-config/files/sbin/openwisp-reload-config

The name "openwisp_config" wasn't consistent with all the other files of the package.
A symbolic link to the old files is provided for backward compatibility.

[change] Changed naming of agent file and init for consistency

---

openwisp-config/Makefile

The postinst/postrm directives must use `IPKG_INSTROOT` because they are executed by the image builder as well.
See: 
* https://github.com/openwrt/packages/blob/master/utils/zsh/Makefile#L101 as an example
* https://openwrt.org/docs/techref/initscripts#enable_and_disable for initscripts

[fix] Fix postinst/postrm in Makefile

---

.github/workflows/ci.yml
runbuild

Closes #216
Please [open a new issue](https://github.com/openwisp/openwisp-config/issues/new/choose) if there isn't an existing issue yet.
Use Ubuntu 24.04 for build OS

[ci] Build package on OpenWrt 23.05 branch #216

---

openwisp-config/Makefile

Remove the symlink with the previous name because
otherwise the service would exist twice with different names.

[fix] Remove symlink to initscript with previous name

---

.github/dependabot.yml
.github/workflows/ci.yml
openwisp-config/files/openwisp.agent

[ci] Added dependabot and upgraded GitHub actions

---

openwisp-config/files/sbin/openwisp-get-address.lua

Fixes [#224](https://github.com/openwisp/openwisp-config/issues/224).
* Added support for getting the IPv6 address if the IPv4 address is not found in `openwisp-get-address`.

Fixes #224: Added ipv6 support to `openwisp-get-address`
